sonar.projectKey=GestionCalidadAPI
sonar.projectName=GestionCalidadAPI
sonar.sources=.
sonar.exclusions=node_modules/**
sonar.host.url=http://localhost:9000
sonar.token=sqp_53afc483365f8b4e4f87bb753588ffa0adaa83c3