sonar.projectKey=GestionCalidadAPI
sonar.projectName=GestionCalidadAPI
sonar.sources=.
sonar.exclusions=node_modules/**
sonar.host.url=http://localhost:9000
sonar.login=sqp_5caaf7dc8a6c33cd591a198b8baf2e8a18742cc3