sonar.projectKey=GestionCalidadAPI
sonar.projectName=GestionCalidadAPI
sonar.sources=.
sonar.exclusions=node_modules/**
sonar.host.url=http://localhost:9000
sonar.login=squ_275d21f8fe0ae2e419bea51bcc425216b16a17f1